# Generated by Django 4.2.27 on 2026-02-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Criminal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                ("crime_type", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="criminals/")),
                ("label", models.IntegerField(unique=True)),
            ],
        ),
    ]
